### ISSUE TITLE
similar criteria vs. than similar license (Indira Bhatt)

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#24]
`3.4  open source - software subject to one or more licenses that meet the Open Source Definition published by the Open Source Initiative [2] or the Free Software Definition [1] or similar license`

We are trying to say that open source =  the licenses meet the definitions/criteria described by the OSI or FSF correct? I think this could be reworded to similar criteria rather than similar license.

**Comment by MarkGisi** [comment]
Shane Comment - Hi Indira, I also understand our intent to date - defer to Mark - is to accept licenses that are listed as meeting the Open Source Definition or Free Software Definition and allow freedom of choice to select licenses not necessarily listed by the OSD or FSD. I am not sure why “similar license” was chosen as the wording but suggest we do not change it at this juncture unless we can confirm the change would not alter meaning. Let’s see if anyone comments :)

**Comment by silverhook** [comment]
I would say the difference can be substantial:

- “or similar license”: includes licenses that are not explicitly identified by either OSI or FSF as OSS or FS respectively, but which still comply to either of the two definitions
- “or similar criteria”: includes licenses that are “FOSS” by definitions that are completely external to OSI and FSF, but are somehow still close enough (by what standard?)

Taking Commons Clause and the SSPL as examples, I cannot see how it qualify under the “or similar licenses”, but can see how (depending on the spin) it might qualify under the “or similar criteria”.

Although that definition seems to be pretty much the same since Spec 1.0, if I were to guess, I would assume that in an early draft the definition of “Open Source” was referring to _licenses listed_ by OSI and FSF as OSS and FS. In that case it makes sense to refer to “similar licenses” to expand the two narrow lists by those licenses that are not (yet) on them, yet should reasonably qualify to be. I would also imagine what happened then was that in a later draft someone (correctly) pointed out that a much more elegant and correct solution would be to instead lean on the definitions of OSS and FS instead of the irregularly curated lists. So, I assume the “or similar licenses” is just an obsolete remnant from an early draft that was forgotten to be removed.

If anything, I would be in favour of simply removing the “or similar license” and keeping the rest of the definition as is. That would remove the confusion, while IMHO still including all relevant licenses we want to cover.

…or does anyone see any gaping holes if the definition read:

> “Open Source” - software subject to one or more licenses that meet the Open Source Definition
published by the Open Source Initiative (OpenSource.org) or the Free Software Definition published by the Free Software Foundation).

It might make sense to provide direct links to the two definitions though.

**Comment by MarkGisi** [comment]
This was discussed at the OpenChain F2F meeting at the Open Source Summit - 2019 (San Diego). 

The definition of Open Source has always sparked lively debate. Although some might agree with the "similar criteria" clarification, an equal number could easily disagree - which is reflected in the above discussion. And Although it has been acknowledged that the definition is not ideal, it seems to be generally accepted (for now). This does not mean we should not revisit the definition over time. Given the requirement that we will only make minimal clarification changes to the spec, it was decide this would not qualify as such for version 2.1. This would be a relevant topic for the next major spec revision, and for that reason we will not close this issue.

**Comment by andrewjskatz** [comment]
I suggest this terminology remains as is. It's not the purpose of the OpenChain Specification to cover software which is exclusively open source, therefore any sensible program will deal with use cases where components which are licensed under terms which are similar to an open source licence, but which are not. For example, it's arguable whether JSON is open source (if you accept that outlawing use for evil discriminates against a field of endeavour), or, various of the CC licences such as ND or NC. There are plenty of other examples. Note that most of the licence scanners deal with code which is not technically open source, and also that SPDX lists some non-open-source licences (which is a sensible decision).
