### ISSUE TITLE
competence for each program participant record

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#29]
1.2.3 Documented evidence of assessed competence for each program participant.

how should in practice such documented evidence look like?

**Comment by silverhook** [comment]
The issue I see here is not that much regarding keeping documentation on who received training (or awareness, since 2.0), but instead how “Program personnel” that is leading the “Program” is to have their competence assessed. It seems a bit like a who watches the watchmen issue, where the people overlooking the Program are the best suited to assess their own competence.

I think the wording of the description is even more odd than that of the verification material:

> Retain appropriate documented information as evidence of competence.

I guess the unwritten convention is that this is a pretty vague definition and anything from “Person X is an internationally renowned FOSS expert” to quoting that this expertise is part of their job requirement, would suffice.

Perhaps this is not as much a Spec issue than a question of how to clarify this in examples, FAQ or other explanatory materials.

**Comment by MarkGisi** [comment]
This was discussed at the F2F meeting at the Open Source Summit - 2019 (San Diego).

>> Perhaps this is not as much a Spec issue than a question of how to clarify this in examples, 

This was the general understanding. As with each requirement - there is flexibility to how one can implement a requirement. It is the project's intent for others to publish the different ways they satisfy each requirement. It is hoped that over time multiple parties will document how they implemented it.
