### ISSUE TITLE
 Software Staff vs Program participant

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#30]
1.3: I take note that Software Staff is not the same as Program 
personnel. Which lowers the bar considerably. It is not entirely clear 
to me though whether Program personnel (kinda defined in Definitions) 
is the same as Program participants, or whether the latter are 
actually Software Staff. Needs clarification IMHO.

**Comment by silverhook** [comment]
After the last call (5 Aug), it seems there is agreement that “Program personnel” and “Program participants” are the same thing. So the text should just be adapted to call them by one, instead of two names, or clarify in definitions that a “Program participant” is a member of the “Program personnel”. It seems this was a simple lapsus calami.

Whether in practice “Program personnel” should replace “Software Staff” throughout the spec, is the big question, but one that probably can wait a major revision.

**Comment by MarkGisi** [comment]
This was discussed at the F2F meeting at the Open Source Summit - 2019 (San Diego). 

It was agreed that "Software Staff" vs "Program Participant" were intended to mean the same thing. It was decided to replace each use of "Software Staff" with "Program Participant"  in version 2.1 of the spec which is more consistent with ISO terminology.

**Comment by silverhook** [comment]
@MarkGisi, so I understand correctly from 2.1 onwards it “Software Staff”, “Program Participant” and “Program Personnel” will all be the same thing?

**Comment by silverhook** [comment]
@MarkGisi, so, if I understand correctly, from 2.1 onward it is:

- “Program Participant” – everyone who is in any way involved with the Program (including what was previously “Software Staff”)
- “Program Personnel” – the people in charge of the Program
