### ISSUE TITLE
Scope - for next iteration

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#33]
The scope clause refers to software solutions _comprised_ of open source software. This suggests that the supplied software consists exclusively of open source software. It would reflect reality more if programs for which the output was not necessarily open source software, but which contained open source, were capable of being included. 

For this reason, I suggest that we change this to _containing_ open source software. This also impacts on 3.2 (_from which the supplied software is comprised_ should read _contained within the supplied software_), and also 4.3.1 similarly.

**Comment by MarkGisi** [comment]
Ok. This would be a good discussion for the next major spec revision.

**Comment by Jimmy-ahlberg** [comment]
To add to this discussion since the topic is still open, and building on Andrews comment above (Which I support since its clearer at least to me as a non native speaker).

Should it read as "_MAY contain_" open source. As unlikely as it may be, an entity may ship software that does not contain open source.  That entity may still have all the other elements of the specification and wish to claim conformance.

**Comment by shanecoughlan** [comment]
We discussed this in two venues: the Monthly Call 2022-12-06 and the OpenChain Mini-Summit at Open Compliance Summit (2022-12-08).

Consensus on the first point - Andrew's suggested change to the Scope definition - was positive. It has been added to the draft specification:
https://github.com/OpenChain-Project/License-Compliance-Specification/blob/master/Official/en/3.0/openchain-license-compliance-3.0.md

**Comment by shanecoughlan** [comment]
@andrewjskatz your point that this also impacts 3.2 appears to actually refer to 2.2 (2.2 - identified licenses). Can you confirm before we do any editing there?

Additionally, since your initial comment I think some sections were renumbered - hence above - can you also flag what was 4.3.1? The spec ends at 3.x in ISO/IEC 5230.

**Comment by shanecoughlan** [comment]
@Jimmy-ahlberg I think "may contain" is solid. We would need to socialize it on the next call in January to ensure agreement before committing.

**Comment by andrewjskatz** [comment]
There are 6 instances of "comprised" in the specification 2.1, of which 5 of them are pertinent to this issue (Intro, 1, 2.2, 3.3.1, 3.3.1.1). The only one that isn't is 2.5). I hope that helps!

**Comment by Dr-wood** [comment]
@shanecoughlan In the meeting today (North America/Europe) we discussed this issue among the participants and determined that we are in agreement that the word "comprised" should be replaced by the words "may contain" as a better alternative.  This issue can be merged and closed with your agreement.
Chris

**Comment by shanecoughlan** [comment]
Addressed and closed with this commit: https://github.com/OpenChain-Project/License-Compliance-Specification/commit/4ba4e101ab7a7228788f5dc0001774d77cdfa38b

**Comment by shanecoughlan** [comment]
Closed as per: https://github.com/OpenChain-Project/License-Compliance-Specification/commit/4ba4e101ab7a7228788f5dc0001774d77cdfa38b
