### ISSUE TITLE
v2.1 § 3.1.5.1 - on integrating code from third parties

### ISSUE THREAD

**Issue by ossguy** [OpenChain-Project/License-Compliance-Specification#46]
As requested on the OpenChain Project Specification Work Group mailing list, I am submitting the following public comment.  I was unable to add this as a pull request, since I couldn't find the source code for v2.1 (only v2.0 and earlier are at https://github.com/OpenChain-Project/Specification/tree/master/version with no branches aside from master).  If I am looking for the v2.1 source code in the wrong place (i.e. for the https://wiki.linuxfoundation.org/_media/openchain/openchainspec-2.1.draft.pdf document), please let me know.  Anyway, here is the suggestion:

Add to the end of Section 3.1.5.1 (after "by each identified license."):

"If software provided by a third party is entering the program's scope, a program participant should ensure that this software's identified license list is correct, and contains the necessary compliance artifacts so that when included in the supplied software all license obligations can be met."

The above notes a particularly problematic area for many companies: since they are responsible for the compliance of all code they distribute to other parties, they need to be extra careful with code received from third parties that they are passing on, as these third parties may not have the same level of rigor in their compliance practices.  So as a reminder, include this mention that companies do need to be especially careful with such third party software, as not all third party companies are OpenChain conformant and/or have other procedures to ensure license compliance, as my experiences have shown.

Denver Gingerich
Software Freedom Conservancy

**Comment by zvr** [comment]
I don't think the spec should contain "reminders" for people to really do what it says...

And 3.1.5 only talks about having a process for reviewing licenses.

**Comment by MarkGisi** [comment]
Although the intentions of a company to verify all their suppliers are compliant is good, I don't see it as practical  yet given the varying degrees of open source maturity of the different suppliers. For example, this would not be feasible in the automotive industry today. We hope, as a first step, that companies would require all their suppliers become OpenChain conforming, but we understand that would still be a big stretch today. 

The goal of OpenChain is to establish trust around compliance between two organizations exchanging software - so that the software recipient does not need to manually verity the quality of compliance artifacts of all their suppliers.
