### ISSUE TITLE
Move "Access" to be part of "Compliance Artifact Delivery"

### ISSUE THREAD

**Issue by zesoup** [OpenChain-Project/License-Compliance-Specification#53]
(referencing numbers via Openchain2.1 RC4)
I’d like to suggest moving 3.2.1 to 3.4. for spec 3.0 

“3.2 Relevant Tasks defined and supported” is the supporting chapter for organizational policies from 3.1. “3.2.1 – Access” however does not directly support existing organizational policies as it governs an external method for inquiry. It is a compliance-artifact-centered requirement, as most compliance inquiries should be answerable by observing or delivering compliance artifacts.
 
Positioning 3.2.1 below 3.4 “Compliance artifact creation and delivery” suggests the process to be more tightly understood in the context of compliance artifacts and that these, most notably the SBoM, be understood as tools that should be able to answer compliance inquiries.

**Comment by stephenkilbaneadi** [comment]
Hmm. Not sure. That might be down to the kind of inquiry you're expecting 3.2.1 to handle. If it's "What OSS do you use in this product?" then, sure, "Here, have an SBOM" addresses is. If it's "where is the source for component X?" then, again, that falls under compliance artefact delivery. On the other hand, if the inquiry is "I think you're out of compliance because of (reasons) - what are you going to do about it?" then dealing with that seems more suited to be under 3.2 which makes sure that you have resources for dealing with the things you need people to be doing.

**Comment by heliocastro** [comment]
Closing this one as decided not feasible subject to be pursue.

**Comment by shanecoughlan** [comment]
Just adding some background context as an additional note.

The issue was opened with the suggestion that Section 3.2.1 be moved into Section 3.4 of the Specification.

== 3.2.1 - Access ==

Maintain a process to effectively respond to external open source inquiries. Publicly identify a means by which a third party can make an open source compliance inquiry.

Verification material(s):

3.2.1.1 - Publicly visible method that allows any third party to make an open source license compliance inquiry (e.g., via a published contact email address, or the Linux Foundation's Open Compliance Directory).
3.2.1.2 - An internal documented procedure for responding to third party open source license compliance inquiries.

== 3.4.1 - Compliance artifacts ==

A process shall exist for creating the set of compliance artifacts for the supplied software.

Verification material(s):

3.4.1.1 - A documented procedure that describes the process under which the compliance artifacts are prepared and distributed with the supplied software as required by the identified licenses.
3.4.1.2 - A documented procedure for archiving copies of the compliance artifacts of the supplied software - where the archive is planned to exist for a reasonable period of time (Determined by domain, legal jurisdiction and/or customer contracts) since the last offer of the supplied software; or as required by the identified licenses (whichever is longer). Records exist that demonstrate the procedure has been properly followed.

== End ==

Specification sections from https://github.com/OpenChain-Project/License-Compliance-Specification/blob/master/Official/en/ISO-5230-2020/ISO-5230-2020.md

It was decided that moving 3.2.1 into 3.4 would narrow the purpose of a contact point from a corporate touchpoint for open source compliance and other questions into a confined role for compliance artifact delivery. The participants on the monthly call of 2023-04-04 decided this would narrow the utility of the role to the potential deteriment of the compliance program.
