### ISSUE TITLE
Definitions: Supplied Software

### ISSUE THREAD

**Issue by MarcelScholze** [OpenChain-Project/License-Compliance-Specification#55]
We should include "other legal entity" as an example for third parties, as some people might not consider another legal entity within their organization as an 'other organization'. 

Suggestion:

"Supplied Software" - software that an organization distributes to third parties (e.g., **other legal entities,** other organizations or individuals).

**Comment by shanecoughlan** [comment]
Yup.

**Comment by Jimmy-ahlberg** [comment]
Raising a point here that been raised internally. If we are developing an internal product, and are following OpenChain 2.1 we would like to claim conformance for that internal product. Internal products have a tendency to sooner or later make their way outside the company, thus there is a value to already from the beginning have it developed in a OpenChain conformant manner and be able to claim this.  

In our case that's not an issue since any internal product would also be distribute to many different legal entities. But for an SME with only one legal entity, but many different product teams it could be relevant.

**Comment by shanecoughlan** [comment]
To clarify my "yup" above, our monthly calls in November and December 2022 featured discussion and consensus that Marcel's suggestion works. It is now included in the 3.0 draft:
https://github.com/OpenChain-Project/License-Compliance-Specification/blob/master/Official/en/3.0/openchain-license-compliance-3.0.md

**Comment by shanecoughlan** [comment]
@Jimmy-ahlberg noted and agreed. I do not think this requires an adjustment to language on the specification, but it is something that we should unpack on the "sales proposition" of the spec.

Closing issue now, reopen as needed.
